### PR TITLE
ENTSWM-192: Update prod booster to Swarm 7.0.0.CR2 (openshift free)

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by balunasj** [comment]
FYI - we don't want to release this live online until after it's released live.

**Comment by gastaldi** [comment]
Is this PR safe to merge?

**Comment by balunasj** [comment]
@heiko-braun knows for sure, but I do not believe so, we don't want to push CR2/GA live until libraries are in place.

**Comment by heiko-braun** [comment]
@gastaldi does merging mean it goes live? I did assume there is an additional release step on your end before it goes live.

@balunasj with "libraries in place" you mean everything in the public red hat maven repositories?

**Comment by heiko-braun** [comment]
@gastaldi there is also the `next` counterpart to this. Do your concerns also apply to that one? https://github.com/fabric8-launch/booster-catalog/pull/123

**Comment by gastaldi** [comment]
@heiko-braun merging means that it goes live in the staging environment (https://launch.prod-preview.openshift.io/). It goes to production when we tag the booster-catalog repository

**Comment by gastaldi** [comment]
To go live, after tagging the booster catalog, we need to file an issue in https://gitlab.cee.redhat.com/dtsd/housekeeping/issues to have the Service Delivery team perform the necessary changes in the production env, like in https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/643

**Comment by heiko-braun** [comment]
@gastaldi thanks for the clarification

**Comment by heiko-braun** [comment]
@gastaldi one more question: 

You said 

> @heiko-braun merging means that it goes live in the staging environment (https://launch.prod-preview.openshift.io/). It goes to production when we tag the booster-catalog repository

If something is merged onto `next` does it have the same impact?

**Comment by gastaldi** [comment]
Yes

Em 1 de nov de 2017 18:54, "Heiko Braun" <notifications@github.com>
escreveu:

@gastaldi <https://github.com/gastaldi> one more question:

You said

@heiko-braun <https://github.com/heiko-braun> merging means that it goes
live in the staging environment (https://launch.prod-preview.openshift.io/).
It goes to production when we tag the booster-catalog repository

If something is merged onto next does it have the same impact?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fabric8-launch/booster-catalog/pull/124#issuecomment-341239273>,
or mute the thread

**Comment by Ladicek** [comment]
There's a lot of insight in this discussion -- @gastaldi WDYT about capturing it in this repo's README?

**Comment by quintesse** [comment]
@heiko-braun 

> why don't I see it in https://launch.prod-preview.openshift.io/ ?

Probably because the backend service wasn't restarted since that PR was merged.

**Comment by gastaldi** [comment]
@ladicek will do, thanks

**Comment by gastaldi** [comment]
@heiko-braun can we merge this PR too?

**Comment by heiko-braun** [comment]
@gastaldi I was told this can happen when the MRRC repo is fully loaded with the prod binaries, which is still not the case. So, no please hold it back. But to be honest, I don't understand why `free` is hold back and `next` is already merged. Shouldn't the MRRC repo policy apply to both? 

@balunasj Maybe you can shed some light on this

**Comment by gastaldi** [comment]
@heiko-braun I added you as a collaborator in this repository, so feel free to merge when ready

**Comment by heiko-braun** [comment]
Muchas gracias!

**Comment by heiko-braun** [comment]
Superceded by #137

**Pull request closed without merging**
