### PR TITLE
Update vert.x booster versions.

### PR DESCRIPTION
**Pull request by cescoffier**
Use CR1 bits - do not merge before CR1 artifacts are made available in a Maven repository.

### CODE REVIEW

**Comment by Ladicek** [comment]
Not sure why this can't be merged -- it's for the `next` branch. Swarm booster updates for CR1 were merged to the catalog just fine (#123), it's just the `openshift-online-free` branch that we need to wait with. I think.

**Comment by quintesse** [comment]
So merge or not? :)

**Comment by gastaldi** [comment]
Is this PR safe to be merged?

**Comment by cescoffier** [comment]
Making a few updates, and will merge it later Today.

**Pull request merged**
