### PR TITLE
OBST-454: Suppress s2i launch for SSO booster

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
Please hold this for now

**Comment by cescoffier** [comment]
Once merged, I will provide a copycat for Vert.x.

**Comment by gastaldi** [comment]
@cescoffier slacker 😆

**Comment by lholmquist** [comment]
same for node :)

**Comment by balunasj** [comment]
@quintesse Heiko is on PTO until Thursday, and said he was all set with this pending the support in the launcher.  Please go ahead and merge this.

**Comment by quintesse** [comment]
Ok, will do @balunasj !

**Pull request merged**
