### PR TITLE
ENTSWM-233: Re-release boosters to include QE found defects (next)

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by Ladicek** [comment]
Can we get this PR merged (and maybe also #135), so that we can test against the `next` branch of the booster catalog? This won't propagate to the running `developers.redhat.com/launch`, that uses the `openshift-online-free` branch of the catalog.

**Comment by heiko-braun** [comment]
> This won't propagate

How do we know that for sure? The reason for holding back was to wait for MRRC updates

**Comment by gastaldi** [comment]
@heiko-braun because production does not use the `next` branch, only `openshift-online-free` and the latest tagged version of this repository

**Comment by Ladicek** [comment]
We need guidelines for dealing with various catalog branches. Currently, different teams treat them differently, which is painful.

**Comment by gastaldi** [comment]
@Ladicek @heiko-braun  there are only 2 branches: `next` and `openshift-online-free`. The README in https://github.com/fabric8-launch/booster-catalog/#booster-catalog explains where these branches are used. Maybe we need to improve that by saying that `next` is used in the staging environment only

**Pull request merged**
